INSERT INTO categories (id, name, description) VALUES (2, 'Programming', 'Dive into the world of coding with our comprehensive programming courses. Whether you''re a beginner or an experienced developer, our courses cover a variety of programming languages and topics, from Python and JavaScript to Java and C++. Learn to build websites, mobile apps, software, and more, and unlock endless possibilities in the digital realm.');
INSERT INTO categories (id, name, description) VALUES (5, 'Design', 'Unleash your creativity and unleash the power of design with our inspiring courses. From graphic design and user experience (UX) design to web design, animation, and multimedia production, our courses cover a variety of design disciplines. Learn to create stunning visuals, develop intuitive user interfaces, and bring your creative ideas to life. Whether you''re a novice designer or a seasoned professional, our courses will help you sharpen your skills and stay ahead in the ever-evolving world of design.');
INSERT INTO categories (id, name, description) VALUES (4, 'Business', 'Elevate your business acumen with our wide range of business courses. From entrepreneurship and management to finance, strategy, and leadership, our courses cover all aspects of running a successful business. Gain practical skills, learn from real-world case studies, and discover innovative approaches to solving business challenges. Whether you''re an aspiring entrepreneur or a seasoned executive, our courses will help you achieve your business goals.');
INSERT INTO categories (id, name, description) VALUES (3, 'Marketing', 'Explore the dynamic field of marketing through our expert-led courses. From digital marketing strategies to social media advertising and market research, our courses provide you with the knowledge and skills needed to excel in today''s competitive market. Gain insights into consumer behavior, learn to create compelling campaigns, and take your marketing career to new heights.');
INSERT INTO categories (id, name, description) VALUES (1, 'Data Science', 'Delve into the world of data science and analytics with our cutting-edge courses. Learn to extract valuable insights from data, master machine learning algorithms, and unleash the power of data-driven decision-making. Whether you''re interested in data visualization, predictive modeling, or big data technologies, our courses will equip you with the skils needed to thrive in this rapidly evolving field.');
INSERT INTO categories (id, name, description) VALUES (7, 'Operating System', 'This is test add category');
INSERT INTO categories (id, name, description) VALUES (8, 'Test2', 'test2aa');



INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (5, 1, 'Introduction to SQL', 'Chapter 1', 'https://www.example.com/sql_intro_video', 'https://www.example.com/sql_intro_attachment', 'Master SQL fundamentals for data science. Learn to retrieve, manipulate, and analyze data with SQL queries, laying a solid foundation for your data science journey.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (20, 13, 'Digital Products with Canva', 'Chapter 1', 'https://www.example.com/canva_digital_products_video', 'https://www.example.com/canva_digital_products_attachment', 'Unlock your creativity with this practical course on Canva. Learn how to design stunning digital products, including social media graphics, presentations, and more, with ease.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (21, 13, 'Principles of UX/UI Design', 'Chapter 2', 'https://www.example.com/ux_ui_design_principles_video', 'https://www.example.com/ux_ui_design_principles_attachment', 'Discover the principles of user experience (UX) and user interface (UI) design with this foundational course. Learn how to create intuitive and visually appealing digital experiences that delight users.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (22, 13, 'Interaction Design Fundamentals', 'Chapter 3', 'https://www.example.com/interaction_design_fundamentals_video', 'https://www.example.com/interaction_design_fundamentals_attachment', 'Learn the fundamentals of interaction design, including user research, prototyping, and usability testing, to create engaging digital experiences.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (8, 1, 'SQL Performance Optimization', 'Chapter 4', 'https://www.example.com/sql_performance_video', 'https://www.example.com/sql_performance_attachment', 'Optimize your SQL queries and database performance with best practices and optimization techniques.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (9, 1, 'SQL Case Studies and Projects', 'Chapter 5', 'https://www.example.com/sql_case_studies_video', 'https://www.example.com/sql_case_studies_attachment', 'Apply your SQL skills to real-world case studies and projects to reinforce learning.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (6, 1, 'SQL Joins and Aggregations', 'Chapter 2', 'https://www.example.com/sql_joins_aggregations_video', 'https://www.example.com/sql_joins_aggregations_attachment', 'Learn about different types of joins and how to use aggregate functions in SQL queries.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (7, 1, 'Advanced SQL Techniques', 'Chapter 3', 'https://www.example.com/advanced_sql_video', 'https://www.example.com/advanced_sql_attachment', 'Explore advanced SQL topics such as subqueries, window functions, and stored procedures.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (23, 13, 'Responsive Web Design', 'Chapter 4', 'https://www.example.com/responsive_web_design_video', 'https://www.example.com/responsive_web_design_attachment', 'Master the principles and techniques of responsive web design to create websites that adapt seamlessly to various devices and screen sizes.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (24, 13, 'Advanced UI Prototyping', 'Chapter 5', 'https://www.example.com/advanced_ui_prototyping_video', 'https://www.example.com/advanced_ui_prototyping_attachment', 'Explore advanced techniques and tools for UI prototyping to create interactive and high-fidelity prototypes for web and mobile applications.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (14, 4, 'Java Project Development', 'Chapter 5', 'https://www.example.com/java_project_video', 'https://www.example.com/java_project_attachment', 'Work on a hands-on Java project to apply your knowledge and build a practical application.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (12, 4, 'Data Structures and Algorithms in Java', 'Chapter 3', 'https://www.example.com/java_ds_algo_video', 'https://www.example.com/java_ds_algo_attachment', 'Explore common data structures and algorithms implemented in Java with practical examples.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (10, 4, 'Introduction to Java Programming', 'Chapter 1', 'https://www.example.com/java_intro_video', 'https://www.example.com/java_intro_attachment', 'A beginner-friendly introduction to Java programming language and its fundamentals.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (18, 7, 'Google Analytics Mastery', 'Chapter 4', 'https://www.example.com/google_analytics_video', 'https://www.example.com/google_analytics_attachment', 'Master Google Analytics to track website traffic, user behavior, and measure marketing effectiveness.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (19, 7, 'Digital Advanced Digital Marketing Strategies', 'Chapter 5', 'https://www.example.com/advanced_digital_marketing_video', 'https://www.example.com/advanced_digital_marketing_attachment', 'Explore advanced digital marketing strategies such as remarketing, A/B testing, and email marketing automation.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (30, 3, 'Introduction to Google Digital Marketing', 'Chapter 1', 'https://www.example.com/google_digital_marketing_intro_video', 'https://www.example.com/google_digital_marketing_intro_attachment', 'An overview of Google Digital Marketing platform and its various tools and features.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (32, 3, 'Google Analytics Setup and Configuration', 'Chapter 3', 'https://www.example.com/google_analytics_setup_video', 'https://www.example.com/google_analytics_setup_attachment', 'Guide to setting up and configuring Google Analytics to track website traffic, conversions, and user behavior.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (33, 3, 'Search Engine Optimization (SEO) Strategies', 'Chapter 4', 'https://www.example.com/seo_strategies_video', 'https://www.example.com/seo_strategies_attachment', 'Learn effective SEO strategies and best practices to improve website visibility and organic search rankings.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (34, 3, 'Social Media Marketing Tactics', 'Chapter 5', 'https://www.example.com/social_media_marketing_tactics_video', 'https://www.example.com/social_media_marketing_tactics_attachment', 'Explore various social media marketing tactics and strategies to engage audiences and drive business results.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (35, 5, 'Introduction to Interaction Design', 'Chapter 1', 'https://www.example.com/interaction_design_intro_video', 'https://www.example.com/interaction_design_intro_attachment', 'An introduction to the principles and concepts of interaction design, including user-centered design and usability.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (36, 5, 'User Research Methods', 'Chapter 2', 'https://www.example.com/user_research_methods_video', 'https://www.example.com/user_research_methods_attachment', 'Learn various user research methods and techniques to gather insights and understand user needs.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (37, 5, 'Wireframing and Prototyping', 'Chapter 3', 'https://www.example.com/wireframing_prototyping_video', 'https://www.example.com/wireframing_prototyping_attachment', 'Master the art of wireframing and prototyping to visually represent and test design concepts and ideas.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (38, 5, 'Usability Testing Techniques', 'Chapter 4', 'https://www.example.com/usability_testing_techniques_video', 'https://www.example.com/usability_testing_techniques_attachment', 'Explore various usability testing techniques and methodologies to evaluate and improve user experience.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (39, 5, 'Designing for Accessibility', 'Chapter 5', 'https://www.example.com/designing_accessibility_video', 'https://www.example.com/designing_accessibility_attachment', 'Guidelines and best practices for designing accessible digital products and interfaces for users with disabilities.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (40, 6, 'HTML Fundamentals', 'Chapter 1', 'https://www.example.com/html_fundamentals_video', 'https://www.example.com/html_fundamentals_attachment', 'Learn the basics of HTML including tags, elements, and structure to create web pages.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (41, 6, 'CSS Styling Techniques', 'Chapter 2', 'https://www.example.com/css_styling_techniques_video', 'https://www.example.com/css_styling_techniques_attachment', 'Explore CSS styling techniques including selectors, properties, and responsive design.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (42, 6, 'JavaScript Essentials', 'Chapter 3', 'https://www.example.com/javascript_essentials_video', 'https://www.example.com/javascript_essentials_attachment', 'Learn essential JavaScript concepts such as variables, loops, and functions for adding interactivity to web pages.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (43, 6, 'Introduction to Frontend Frameworks', 'Chapter 4', 'https://www.example.com/frontend_frameworks_intro_video', 'https://www.example.com/frontend_frameworks_intro_attachment', 'An overview of popular frontend frameworks such as React, Angular, and Vue.js.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (44, 6, 'Backend Development Basics', 'Chapter 5', 'https://www.example.com/backend_development_basics_video', 'https://www.example.com/backend_development_basics_attachment', 'Introduction to backend development concepts including server-side scripting, databases, and APIs.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (45, 8, 'Content Marketing Fundamentals', 'Chapter 1', 'https://www.example.com/content_marketing_fundamentals_video', 'https://www.example.com/content_marketing_fundamentals_attachment', 'Learn the fundamentals of content marketing including content creation, distribution, and measurement.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (46, 8, 'Content Strategy Development', 'Chapter 2', 'https://www.example.com/content_strategy_development_video', 'https://www.example.com/content_strategy_development_attachment', 'Explore strategies for developing effective content marketing strategies aligned with business objectives.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (47, 8, 'Audience Engagement Techniques', 'Chapter 3', 'https://www.example.com/audience_engagement_techniques_video', 'https://www.example.com/audience_engagement_techniques_attachment', 'Discover techniques for engaging target audiences through compelling content and storytelling.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (48, 8, 'Social Media Content Planning', 'Chapter 4', 'https://www.example.com/social_media_content_planning_video', 'https://www.example.com/social_media_content_planning_attachment', 'Learn how to plan and create content tailored for various social media platforms to maximize engagement and reach.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (49, 8, 'Content Marketing Analytics', 'Chapter 5', 'https://www.example.com/content_marketing_analytics_video', 'https://www.example.com/content_marketing_analytics_attachment', 'Explore tools and techniques for measuring and analyzing the performance of content marketing campaigns.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (50, 9, 'Introduction to Facebook Ads', 'Chapter 1', 'https://www.example.com/facebook_ads_intro_video', 'https://www.example.com/facebook_ads_intro_attachment', 'An introduction to Facebook Ads platform and advertising options for businesses.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (51, 9, 'Facebook Ads Targeting Strategies', 'Chapter 2', 'https://www.example.com/facebook_ads_targeting_video', 'https://www.example.com/facebook_ads_targeting_attachment', 'Learn effective targeting strategies to reach the right audience on Facebook and Instagram.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (52, 9, 'Ad Creative and Copywriting', 'Chapter 3', 'https://www.example.com/facebook_ads_creative_video', 'https://www.example.com/facebook_ads_creative_attachment', 'Tips and best practices for creating compelling ad creatives and writing persuasive ad copy for Facebook campaigns.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (53, 9, 'Facebook Ads Optimization Techniques', 'Chapter 4', 'https://www.example.com/facebook_ads_optimization_video', 'https://www.example.com/facebook_ads_optimization_attachment', 'Learn optimization techniques to improve the performance and ROI of your Facebook advertising campaigns.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (54, 9, 'Advanced Facebook Ads Strategies', 'Chapter 5', 'https://www.example.com/advanced_facebook_ads_video', 'https://www.example.com/advanced_facebook_ads_attachment', 'Explore advanced strategies such as retargeting, lookalike audiences, and campaign scaling to maximize Facebook Ads results.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (55, 11, 'Introduction to Financial Markets', 'Chapter 1', 'https://www.example.com/financial_markets_intro_video', 'https://www.example.com/financial_markets_intro_attachment', 'An introduction to financial markets including stocks, bonds, and commodities.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (56, 11, 'Stock Market Analysis', 'Chapter 2', 'https://www.example.com/stock_market_analysis_video', 'https://www.example.com/stock_market_analysis_attachment', 'Learn techniques and tools for analyzing stock market trends, valuing stocks, and making investment decisions.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (57, 11, 'Fundamental Analysis', 'Chapter 3', 'https://www.example.com/fundamental_analysis_video', 'https://www.example.com/fundamental_analysis_attachment', 'An in-depth look at fundamental analysis methods to evaluate the intrinsic value of stocks and assess investment opportunities.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (58, 11, 'Technical Analysis Strategies', 'Chapter 4', 'https://www.example.com/technical_analysis_strategies_video', 'https://www.example.com/technical_analysis_strategies_attachment', 'Explore technical analysis strategies including chart patterns, indicators, and oscillators for timing investment trades.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (59, 11, 'Risk Management in Financial Markets', 'Chapter 5', 'https://www.example.com/financial_markets_risk_management_video', 'https://www.example.com/financial_markets_risk_management_attachment', 'Learn risk management techniques to mitigate investment risks and protect portfolios in financial markets.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (60, 12, 'Strategic Planning Fundamentals', 'Chapter 1', 'https://www.example.com/strategic_planning_fundamentals_video', 'https://www.example.com/strategic_planning_fundamentals_attachment', 'An overview of strategic planning process and fundamentals for developing effective business strategies.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (61, 12, 'Competitive Analysis Techniques', 'Chapter 2', 'https://www.example.com/competitive_analysis_techniques_video', 'https://www.example.com/competitive_analysis_techniques_attachment', 'Learn methods and tools for conducting competitive analysis to identify strengths, weaknesses, and opportunities in the market.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (62, 12, 'Strategic Decision Making', 'Chapter 3', 'https://www.example.com/strategic_decision_making_video', 'https://www.example.com/strategic_decision_making_attachment', 'Explore strategies and frameworks for making strategic decisions to achieve organizational goals and objectives.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (63, 12, 'Business Model Innovation', 'Chapter 4', 'https://www.example.com/business_model_innovation_video', 'https://www.example.com/business_model_innovation_attachment', 'Discover techniques for innovating business models to create value and sustain competitive advantage in dynamic markets.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (64, 12, 'Strategic Implementation and Execution', 'Chapter 5', 'https://www.example.com/strategic_implementation_execution_video', 'https://www.example.com/strategic_implementation_execution_attachment', 'Learn strategies and best practices for effectively implementing and executing business strategies to achieve desired outcomes.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (65, 14, 'Introduction to UX/UI Design', 'Chapter 1', 'https://www.example.com/ux_ui_design_intro_video', 'https://www.example.com/ux_ui_design_intro_attachment', 'An introduction to the principles and concepts of user experience (UX) and user interface (UI) design.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (66, 14, 'User Research and Personas', 'Chapter 2', 'https://www.example.com/user_research_personas_video', 'https://www.example.com/user_research_personas_attachment', 'Learn methods for conducting user research and creating user personas to inform the design process.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (67, 14, 'Information Architecture', 'Chapter 3', 'https://www.example.com/information_architecture_video', 'https://www.example.com/information_architecture_attachment', 'Explore principles of information architecture for organizing and structuring content to improve usability and findability.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (68, 14, 'UI Design Principles', 'Chapter 4', 'https://www.example.com/ui_design_principles_video', 'https://www.example.com/ui_design_principles_attachment', 'Learn essential principles of UI design including layout, typography, color, and visual hierarchy for creating intuitive interfaces.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (69, 14, 'UX Design Process', 'Chapter 5', 'https://www.example.com/ux_design_process_video', 'https://www.example.com/ux_design_process_attachment', 'Explore the UX design process including research, ideation, prototyping, testing, and iteration.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (70, 15, 'Fundamentals of Interaction Design', 'Chapter 1', 'https://www.example.com/interaction_design_chapter1_video', 'https://www.example.com/interaction_design_chapter1_attachment', 'Introduction to interaction design principles and user-centered design methodologies.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (71, 15, 'User Research Methods', 'Chapter 2', 'https://www.example.com/interaction_design_chapter2_video', 'https://www.example.com/interaction_design_chapter2_attachment', 'User research techniques including interviews, surveys, and observation methods for gathering insights.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (72, 15, 'Prototyping Techniques', 'Chapter 3', 'https://www.example.com/interaction_design_chapter3_video', 'https://www.example.com/interaction_design_chapter3_attachment', 'Prototyping tools and methods for creating interactive prototypes and testing design concepts.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (73, 15, 'Usability Testing', 'Chapter 4', 'https://www.example.com/interaction_design_chapter4_video', 'https://www.example.com/interaction_design_chapter4_attachment', 'Usability testing techniques to evaluate the effectiveness and user experience of digital interfaces.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (74, 15, 'Designing for Accessibility', 'Chapter 5', 'https://www.example.com/interaction_design_chapter5_video', 'https://www.example.com/interaction_design_chapter5_attachment', 'Designing for accessibility and inclusive design principles for creating user-friendly experiences for all users.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (25, 2, 'Introduction to Excel Basics', 'Chapter 1', 'https://www.example.com/excel_intro_video', 'https://www.example.com/excel_intro_attachment', 'Introduction to Excel basics covering spreadsheet fundamentals, formulas, and basic data analysis techniques.', 1, 'Beginner', '2024-02-26 11:41:39');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (17, 7, 'Search Engine Optimization (SEO) Basics', 'Chapter 3', 'https://www.example.com/seo_basics_video', 'https://www.example.com/seo_basics_attachment', 'Understand the fundamentals of SEO and techniques to improve website visibility in search engines.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (15, 7, 'Getting Started with Google Digital Marketing', 'Chapter 1', 'https://www.example.com/google_digital_marketing_intro_video', 'https://www.example.com/google_digital_marketing_intro_attachment', 'An overview of digital marketing concepts and strategies with a focus on Google platforms.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (29, 2, 'Excel Automation with VBA', 'Chapter 5', 'https://www.example.com/excel_automation_vba_video', 'https://www.example.com/excel_automation_vba_attachment', 'Introduction to Excel VBA (Visual Basic for Applications) for automating repetitive tasks and extending Excel functionalities.', 1, 'Advanced', '2024-02-26 11:41:39');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (16, 7, 'Google Ads Fundamentals', 'Chapter 2', 'https://www.example.com/google_ads_video', 'https://www.example.com/google_ads_attachment', 'Learn how to create and optimize Google Ads campaigns to reach your target audience effectively.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (13, 4, 'Java GUI Development', 'Chapter 4', 'https://www.example.com/java_gui_video', 'https://www.example.com/java_gui_attachment', 'Create graphical user interfaces (GUIs) using Java Swing and JavaFX frameworks.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (31, 3, 'Chapter Google Ads Campaign Setup', 'Chapter 2', 'https://www.example.com/google_ads_setup_video', 'https://www.example.com/google_ads_setup_attachment', 'Learn how to set up effective Google Ads campaigns, including keyword research, ad creation, and targeting.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (27, 2, 'Advanced Data Analysis with Excel', 'Chapter 3', 'https://www.example.com/advanced_excel_analysis_video', 'https://www.example.com/advanced_excel_analysis_attachment', 'Explore advanced data analysis techniques in Excel, including statistical functions, data modeling, and scenario analysis.', 1, 'Advanced', '2024-02-26 11:41:39');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (26, 2, 'Intermediate Excel Functions', 'Chapter 2', 'https://www.example.com/excel_intermediate_functions_video', 'https://www.example.com/excel_intermediate_functions_attachment', 'Learn intermediate Excel functions such as VLOOKUP, INDEX/MATCH, and PivotTables for more advanced data analysis.', 1, 'Intermediate', '2024-02-26 11:41:39');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (28, 2, 'Excel Dashboard and Reporting', 'Chapter 4', 'https://www.example.com/excel_dashboard_video', 'https://www.example.com/excel_dashboard_attachment', 'Learn to create dynamic Excel dashboards and reports to visualize and communicate data insights effectively.', 1, 'Advanced', '2024-02-26 11:41:39');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (11, 4, 'Object-Oriented Programming in Java', 'Chapter 2', 'https://www.example.com/oop_java_video', 'https://www.example.com/oop_java_attachment', 'Learn about object-oriented programming principles and how to implement them in Java.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (80, 10, 'Launching Your Online Business', 'Chapter 1', 'https://www.example.com/launch_business_chapter1_video', 'https://www.example.com/launch_business_chapter1_attachment', 'Introduction to online business and market research techniques for identifying opportunities and validating business ideas.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (81, 10, 'Building Your Brand', 'Chapter 2', 'https://www.example.com/launch_business_chapter2_video', 'https://www.example.com/launch_business_chapter2_attachment', 'Developing a business plan and defining your value proposition, target audience, and competitive advantage.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (82, 10, 'Creating Your Online Presence', 'Chapter 3', 'https://www.example.com/launch_business_chapter3_video', 'https://www.example.com/launch_business_chapter3_attachment', 'Setting up your online presence including website creation, branding, and content development.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (83, 10, 'Marketing Strategies', 'Chapter 4', 'https://www.example.com/launch_business_chapter4_video', 'https://www.example.com/launch_business_chapter4_attachment', 'Marketing strategies and tactics for attracting customers, building an audience, and driving traffic to your online business.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO chapters (id, course_id, title, name, videopath, attachmentpath, description, status, level, created_at) VALUES (84, 10, 'Scaling Your Business', 'Chapter 5', 'https://www.example.com/launch_business_chapter5_video', 'https://www.example.com/launch_business_chapter5_attachment', 'Scaling your online business, optimizing operations, and planning for long-term growth and sustainability.', 1, 'Advanced', '2024-02-26 11:41:07');



INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (13, 5, 5, 'Digital Products with Canva', 140, 'Unlock your creativity with this practical course on Canva. Learn how to design stunning digital products, including social media graphics, presentations, and more, with ease.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (6, 2, 2, 'Web Development', 60, 'Learn HTML for structure, CSS for styling, and JavaScript for interactivity in this comprehensive course, and create dynamic websites.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (5, 2, 2, 'Crash Course on Python', 90, 'Covering essential Python concepts and syntax, this course is perfect for beginners looking to kickstart their coding journey.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (12, 4, 4, 'Business Strategies', 90, 'Explore strategic thinking and decision-making with this insightful course. Learn how to analyze markets, competitors, and internal capabilities to develop effective business strategies.', 1, 'Advanced', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (4, 2, 2, 'Java Programming', 90, 'Master the fundamentals of Java programming with this concise course. Learn key concepts, syntax, and best practices to start building robust applications.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (7, 3, 3, 'Google Digital Marketing', 120, 'Explore Google Digital Marketing. Gain insights into online advertising, SEO, analytics, and more, and level up your marketing game.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (1, 1, 1, 'Learn SQL Basics', 50, 'Master SQL fundamentals for data science. Learn to retrieve, manipulate, and analyze data with SQL queries, laying a solid foundation for your data science journey.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (3, 1, 1, 'Microsoft Power BI', 90, 'Uncover data analytics with Microsoft Power BI. Create interactive dashboards, visualize data, and make informed decisions in this hands-on course.', 1, 'Advanced', '2024-02-26 11:42:40');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (9, 3, 3, 'Set Up a Facebook Ads', 40, 'Learn the ins and outs of Facebook advertising with this practical course. From ad creation to targeting and optimization, master the skills needed to launch successful ad campaigns.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (8, 3, 3, 'Strategy Content Marketing', 80, 'Discover effective content marketing strategies with this focused course. Learn how to create compelling content, engage your audience, and drive results for your business.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (14, 5, 5, 'Principles of UX/UI Design', 70, 'Discover the principles of user experience (UX) and user interface (UI) design with this foundational course. Learn how to create intuitive and visually appealing digital experiences that delight users.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (11, 4, 4, 'Financial Markets', 80, 'Build your foundational knowledge of financial markets with this informative course. Explore stocks, bonds, derivatives, and navigate the complexities of the financial world.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (10, 4, 4, 'Launch Your Online Business', 160, 'Transform your business idea into reality with this practical course. From market research to branding and launch strategies, it will guide you through starting your own online business.', 1, 'Beginner', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (2, 1, 1, 'Excel Basics For Data Analyst', 40, 'Master Excel essentials for data analysis. Learn formulas, functions, and pivot tables to organize and analyze data efficiently, enhancing your skills as a data analyst.', 1, 'Beginner', '2024-02-26 11:41:39');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (15, 5, 5, 'Interaction Design', 90, 'Explore advanced interaction design in this specialized course. Dive into topics like user research, prototyping, and usability testing to master designing interactive digital products.', 1, 'Intermediate', '2024-02-26 11:41:07');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (16, 7, 12, 'Windows', 50, 'testing', 1, 'Beginner', '2024-03-25 17:25:21.084712');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (20, 7, 12, 'Mac', 80, 'Testing create course', 1, 'Beginner', '2024-03-25 17:58:04.368134');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (21, 7, 12, 'Linux', 120, 'Testing create course linux', 1, 'Intermediate', '2024-03-25 17:58:39.775913');
INSERT INTO courses (id, category_id, tutor_id, name, durations, description, status, difficulties, created_at) VALUES (22, 8, 1, 'Test', 120, 'test', 1, 'Beginner', '2024-03-25 21:58:39.934194');



INSERT INTO enrolls (id, student_id, course_id, date_enroll) VALUES (2, 3, 2, '2024-02-26 11:48:31');
INSERT INTO enrolls (id, student_id, course_id, date_enroll) VALUES (3, 7, 1, '2024-03-25 00:00:00');
INSERT INTO enrolls (id, student_id, course_id, date_enroll) VALUES (4, 7, 2, '2024-03-25 00:00:00');



INSERT INTO roles (id, name, description) VALUES (1, 'Tutor', 'Tutor in this system');
INSERT INTO roles (id, name, description) VALUES (2, 'Student', 'Student in this system');


INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (3, 2, 'Joshua', 'josh@gmail.com', 'abc1234', 'C:\\Users\\user\\assets\\profile_picture\\3', '2024-02-26 11:43:17', '2024-02-26 11:43:17');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (4, 2, 'Osama', 'test@example.com', 'abc1234', NULL, '2024-03-20 22:23:57.781489', '2024-03-20 22:23:57.781489');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (5, 2, 'Abu', 'john@example.com', 'abc1234', NULL, '2024-03-20 22:29:30.302733', '2024-03-20 22:29:30.302733');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (1, 1, 'Jamil Pardi', 'jamil@gmail.com', 'abc1234', 'C:\\Users\\user\\assets\\profile_picture\\1', '2024-02-26 11:30:32', '2024-02-26 11:30:35');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (6, 2, 'Student', 'student@example.com', 'abc1234', NULL, '2024-03-20 22:29:30.302733', '2024-03-20 22:29:30.302733');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (7, 2, 'Faisal Ismail', 'faisal@gmail.com', 'abc1234', 'C:\\Users\\user\\assets\\profile_picture\\2', '2024-02-26 11:34:23', '2024-02-26 11:34:23');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (2, 1, 'Jamal Parda', 'jamal@gmail.com', 'abc1234', NULL, '2024-03-25 15:07:35', '2024-03-20 22:29:30.302733');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (11, 1, 'student1', 'student1@gmail.com', 'abc1234', NULL, '2024-03-25 15:20:08.015052', '2024-03-25 15:20:08.015052');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (12, 1, 'tutor1', 'tutor1@gmail.com', 'abc1234', NULL, '2024-03-25 15:52:20.98949', '2024-03-25 15:52:20.98949');
INSERT INTO users (id, role_id, name, email, password, profile_picture, join_date, created_at) VALUES (10, 1, 'tutor', 'tutor@gmail.com', 'abc1234', NULL, '2024-03-25 15:13:33.166512', '2024-03-25 15:13:33.166512');

